namespace: webapp
releases:
  - name: webapp
    chart: ../charts/webapp
    values:
      - ../charts/webapp/values.yaml
    set:
      image.tag: "latest"
      replicaCount: 3
      service.type: LoadBalancer
      ingress.enabled: true
      ingress.hosts:
        - host: production.example.com
          paths:
            - /
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"