apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-yui-piano-school
  labels:
    app: {{ .Release.Name }}-yui-piano-school
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-yui-piano-school
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-yui-piano-school
    spec:
      containers:
        - name: yui-piano-school
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
