apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-yui-piano-school
  labels:
    app: {{ .Release.Name }}-yui-piano-school
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-yui-piano-school
