apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-registry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-registry
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-registry
    spec:
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 443
          env:
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:443"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/tls.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/tls.key"
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: registry-data
              mountPath: /var/lib/registry
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.ingress.tlsSecretName }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        - name: registry-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-registry-pvc
