apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-registry
