apiVersion: v1
appVersion: "1.0.0"
description: A Helm chart for deploying a web application
name: yui-piano-school
version: 0.1.0

replicaCount: 2

image:
  repository: keitakoba/yui-piano-school
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  name: yui-piano-school
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}
