replicaCount: 1

image:
  repository: registry
  tag: 2.8.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  host: registry.example.com

resources: {}
