image:
  tag: "latest"
replicaCount: 1
service:
  type: LoadBalancer
ingress:
  enabled: false
  hosts:
    - host: production.example.com
      paths:
        - /
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
